#!/bin/sh

Terminal='st'
Choice=$(
  basename -a /usr/share/applications/*.desktop |
  dmenu "$@"
) || exit 0

DesktopFile="/usr/share/applications/$Choice"
DesktopExec=$(sed -n 's/^Exec=//p' "$DesktopFile" | head -n1 | sed -n 's/%[a-zA-z]//p')
DesktopTerminal=$(sed -n 's/^Terminal=//p' "$DesktopFile")

if [ "$DesktopTerminal" = "true" ]; then
  ${SHELL:-"/bin/sh"} -c "$Terminal -e $DesktopExec" &
else
  ${SHELL:-"/bin/sh"} -c "$DesktopExec" &
fi
